### ISSUE TITLE
Disabling an already loaded css file

### ISSUE THREAD

**Issue by paulocoghi** [malko/l.js#12]
Is it possible to disable a CSS file that was loaded by l.js?

When I load css files in traditional way, without l.js, I currently use this method to disable a specific one:
```javascript
// To disable a specific css file
document.getElementsByTagName('link')[2].disabled = true
```

```javascript
// And, to enable it again
document.getElementsByTagName('link')[2].disabled = false
```

Is there a way to accomplish this with l.js?

**Comment by malko** [comment]
Sorry but there's no way or plan to achieve this with _l.js_.
_l.js_ is a loader and its only purpose is to load files. You still can go with your actual method which look fine to me.

**Comment by paulocoghi** [comment]
Is there a way to manually disable a CSS file load by **l.js**? I just need to know where it *stores* the css files so I can manually disable them, when needed.

**Comment by malko** [comment]
when **l.js** load a file it does two things:
- mark internally the file as asked for loading to avoid attempting to loading it again
- create a script or link tag to effectively load the file.

You can in the load callback use your method as you did without **l.js**.
Also you will perhaps appreciate the option to set an id to your link tag to get it by id instead of getByTagName here's an exemple:

```javascript
ljs.load('styles.css#myfancystyle', function() {
    var linkElement = document.getElementById('myfancystyle');
    //... do some work ...
    linkElement.disabled = true;
});
```
 I haven't tested it but it should work.

Tell me if this is ok for you.

**Comment by paulocoghi** [comment]
It works perfectly. Set an id to link tags is the way to go.

Just to clarify, I need to disable specific CSS files some times as a temporary solution/workaround for an application that was designed with conflicting css files.

It was a multi-page app but I am "translating" it to a single page app, and each route still depends on different css files (we are also working on this issue, since is a completely bad practice).

Thanks!

**Comment by malko** [comment]
Cool, i'm pleased it worked for you.
