### ISSUE TITLE
Npm registry

### ISSUE THREAD

**Issue by AlexGal0** [malko/l.js#22]
Hi, @malko 
We are having trouble trying to import l.js, the versions are getting messed up because the bower.json is not updated, it would be helpful if you could register l.js in npm in order to clarify the versions.

Greetings, Marlon.

**Comment by malko** [comment]
In fact does it make sense to have as an npm dependency as well ?
Can you please share with me the way you use l.js in your workflow, it is really interesting for me in order to offer the best dev exp.

**Comment by ivanrey** [comment]
We use it now with Yarn (v1).

We also have some internal scripts that read the version from the lock files and since l.js doesn't have a package.json file it can't detect it. We though it would be nice to have it registered in Yarn (npm) in order to use it directly an not with the github reference (malko/l.js), and it would also help our versioning system to detect the right version in order to invalidate browser caches easier.

**Comment by malko** [comment]
ok understood, I'll publish a version 0.2.2 in the next minutes, it is basically only introducing it as a npm package and a version bump.

**Comment by malko** [comment]
here it is: https://www.npmjs.com/package/@malko/l.js

```npm install @malko/l.js``` should be good to go.

cheers
